<?php

use Illuminate\Support\Facades\Route;

/**
 * Main Web Routes — OmnyRestore
 *
 * This file is the entry point for all web routes.
 * Specific route groups are split into separate files for clarity:
 *   - routes/auth.php    → Breeze auth routes (login, register, password reset, etc.)
 *   - routes/client.php  → Client space (/client/*)  — auth + verified middleware
 *   - routes/admin.php   → Admin back office (/admin/*) — auth + verified + admin middleware
 *   - routes/webhook.php → External webhooks (/webhook/*) — no auth, HMAC verified
 */

// ─── Public Showcase (Landing Page) ───────────────────────────────────────────
// The landing page is the only fully public route.
// No auth required — anyone can visit to learn about the service.
Route::view('/', 'welcome')->name('home');

// ─── Auth Routes (Breeze) ─────────────────────────────────────────────────────
// login, register, logout, email verification, password reset
// Generated by: php artisan breeze:install livewire
require __DIR__.'/auth.php';

// ─── Client Routes ────────────────────────────────────────────────────────────
// /client/orders, /client/orders/{order}, /client/orders/{order}/download, etc.
// Middleware: auth + verified (defined inside client.php)
require __DIR__.'/client.php';

// ─── Admin Routes ─────────────────────────────────────────────────────────────
// /admin/dashboard, /admin/orders, etc.
// Middleware: auth + verified + admin (defined inside admin.php)
require __DIR__.'/admin.php';

// ─── Webhook Routes ───────────────────────────────────────────────────────────
// /webhook/stripe
// CSRF exempt — Stripe HMAC signature is the security mechanism
require __DIR__.'/webhook.php';

