<?php

use Illuminate\Support\Facades\Route;

/**
 * Main Web Routes — OmnyRestore
 *
 * This file is the entry point for all web routes.
 * Specific route groups are split into separate files for clarity:
 *   - routes/auth.php    → Breeze auth routes (login, register, password reset, etc.)
 *   - routes/client.php  → Client space (/client/*)  — auth + verified middleware
 *   - routes/admin.php   → Admin back office (/admin/*) — auth + verified + admin middleware
 *   - routes/webhook.php → External webhooks (/webhook/*) — no auth, HMAC verified
 */

// ─── Public Showcase (Landing Page) ───────────────────────────────────────────
// The landing page is the only fully public route.
// No auth required — anyone can visit to learn about the service.
Route::view('/', 'welcome')->name('home');

// ─── Redirection dashboard (compatibilité Breeze) ──────────────────────────────
// Breeze génère des composants qui font `route('dashboard')` (ex: confirm-password).
// Cette app n'a pas de dashboard générique — on redirige selon le rôle.
// Un admin → /admin/dashboard, un client → /client/orders
Route::middleware(['auth', 'verified'])->get('/dashboard', function () {
    return auth()->user()->isAdmin()
        ? redirect()->route('admin.dashboard')
        : redirect()->route('client.orders.index');
})->name('dashboard');

// ─── Pages légales ────────────────────────────────────────────────────────────
Route::view('/mentions-legales', 'pages.legal.mentions')->name('legal.mentions');
Route::view('/confidentialite', 'pages.legal.privacy')->name('legal.privacy');
Route::view('/conditions-generales-de-vente', 'pages.legal.cgv')->name('legal.cgv');

// ── Stripe redirects ────────────────────────────────────────────────────────
// /payment/success : vérifie la session Stripe et marque l'ordre PAID
// (double filet webhook — fonctionne aussi en local sans tunnel Stripe CLI)
Route::middleware(['auth', 'verified'])->group(function () {
    Route::get('/payment/success', [App\Http\Controllers\Client\PaymentSuccessController::class, 'handle'])
        ->name('payment.success');
});
Route::view('/payment/cancel', 'pages.payment.cancel')->name('payment.cancel');

// ─── Email-gate : déverrouillage de l'aperçu ─────────────────────────────────
// Route publique (pas d'auth) — l'URL signée par Laravel garantit l'authenticité.
// Expire après 7 jours. Une fois cliqué, preview_unlocked_at est renseigné.
// Après redirection vers /client/orders/{order}, le middleware auth prend le relais.
Route::get('/unlock-preview/{order}', App\Http\Controllers\Client\UnlockPreviewController::class)
    ->middleware('signed')
    ->name('client.orders.unlock-preview');


// ─── Auth Routes (Breeze) ─────────────────────────────────────────────────────
// login, register, logout, email verification, password reset
// Generated by: php artisan breeze:install livewire
require __DIR__.'/auth.php';

// ─── Client Routes ────────────────────────────────────────────────────────────
// /client/orders, /client/orders/{order}, /client/orders/{order}/download, etc.
// Middleware: auth + verified (defined inside client.php)
require __DIR__.'/client.php';

// ─── Admin Routes ─────────────────────────────────────────────────────────────
// /admin/dashboard, /admin/orders, etc.
// Middleware: auth + verified + admin (defined inside admin.php)
require __DIR__.'/admin.php';

// ─── Webhook Routes ───────────────────────────────────────────────────────────
// /webhook/stripe
// CSRF exempt — Stripe HMAC signature is the security mechanism
require __DIR__.'/webhook.php';

