<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Migration: Create the order_deliveries table
 *
 * This table stores the generated ZIP archive for each completed order.
 * It is separate from orders for several reasons:
 *   1. Not every order reaches the delivery stage (CANCELLED orders don't)
 *   2. The ZIP path and signed URL are derived data, not core order data
 *   3. The signed URL has a TTL and needs to be regenerated — separation of concerns
 *
 * Security architecture:
 *   - The ZIP file on S3 is in a private bucket (no public access)
 *   - Clients NEVER get a direct S3 URL
 *   - All downloads go through: GET /client/orders/{id}/download
 *     → Laravel verifies auth + payment + ownership
 *     → Generates a fresh presigned URL (TTL: 48h)
 *     → Returns a 302 redirect to the presigned URL
 *   - S3 enforces the TTL — the URL becomes invalid after 48 hours
 *
 * @see App\Models\OrderDelivery
 * @see App\Jobs\GenerateOrderZipJob
 * @see App\Jobs\GenerateSignedDownloadUrlJob
 * @see App\Http\Controllers\Client\OrderDownloadController
 */
return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('order_deliveries', function (Blueprint $table) {
            // ─── Primary Key ─────────────────────────────────────────────
            $table->uuid('id')->primary();

            // ─── Relationship ─────────────────────────────────────────────
            // One order can have only one delivery (one ZIP per order).
            // The unique constraint prevents duplicate delivery records.
            $table->foreignUuid('order_id')
                  ->unique()
                  ->constrained('orders')
                  ->onDelete('cascade'); // If order is deleted, delete its delivery

            // ─── ZIP Storage Location ─────────────────────────────────────
            // The disk name (filesystem driver) where the ZIP is stored.
            // In production: 's3' (or 'delivery' — a separate S3 bucket)
            // In local dev: 'local' (storage/app/deliveries/)
            $table->string('zip_disk')->default('s3');

            // The full path to the ZIP file within the disk.
            // Format: deliveries/{order_uuid}/ORD-2026-XXXX_restauration.zip
            $table->string('zip_path');

            // File size in bytes — stored for display in the client's download page
            $table->unsignedBigInteger('zip_size')->nullable();

            // ─── Presigned URL ────────────────────────────────────────────
            // The signed URL is generated by S3 and has a limited TTL.
            // We cache it in the DB to avoid regenerating on every page load.
            // When expired, the download controller regenerates it on-demand.
            $table->text('signed_url')->nullable();
            $table->timestamp('signed_url_expires_at')->nullable();

            // ─── Download Tracking ─────────────────────────────────────────
            // Number of times the client has downloaded this ZIP.
            // Informational — not used for access control.
            $table->unsignedSmallInteger('download_count')->default(0);
            $table->timestamp('last_downloaded_at')->nullable();

            // ─── Timestamps ───────────────────────────────────────────────
            $table->timestamps(); // created_at = ZIP generation timestamp
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('order_deliveries');
    }
};
